[package]
name = "proc-macro-hack-impl"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Procedural functionlike!() macros using only Macros 1.1"
repository = "https://github.com/dtolnay/proc-macro-hack"

[lib]
proc-macro = true
