sudo: false

language: rust

rust:
  - nightly
  - beta
  - stable
  - 1.31.0

script:
  - cargo run --manifest-path example/Cargo.toml

matrix:
  include:
    - rust: nightly
      name: Minimal versions
      before_script:
        - cargo update -Z minimal-versions --manifest-path example/Cargo.toml
    - rust: 1.30.0
      name: 2015 edition
      script:
        - cargo check
